language: haskell

before_install:
    - git submodule update --init --recursive
    - sudo cabal install gtk2hs-buildtools --global
    - cabal install fun/equ/equ.cabal
    - cabal install fun/fun.cabal
